apiVersion: 1
groups:
    - orgId: 1
      name: Status Page Critical Alerts
      folder: Alerts
      interval: 1m
      rules:
        - uid: sp-cpu-crit-v2
          title: SP CPU Critical
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                expr: sum(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"status-page.*"}[5m])) by (pod) * 100
                instant: true
                interval: ""
                intervalMs: 30000
                legendFormat: '{{pod}}'
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.01
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: yoav-dashboard-v4
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: yoav-dashboard-v4
            __panelId__: "1"
            description: The pod {{ $labels.pod }} has exceeded 0.01% CPU
            summary: CPU Alert on {{ $labels.pod }}
          labels:
            severity: critical
          isPaused: false
        - uid: sp-pod-crit-v2
          title: SP Pod Status Critical
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                expr: max by (pod) (kube_pod_status_ready{namespace="default", condition="true", pod=~"status-page.*"})
                instant: true
                interval: ""
                intervalMs: 30000
                legendFormat: '{{pod}}'
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: yoav-dashboard-v4
          panelId: 3
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: yoav-dashboard-v4
            __panelId__: "3"
            description: Pod {{ $labels.pod }} is DOWN
            summary: Pod DOWN Alert
          labels:
            severity: critical
          isPaused: false
