apiVersion: 1
contactPoints:
    - orgId: 1
      name: telegram-alerts
      receivers:
        - uid: afezus974bri8c
          type: telegram
          settings:
            bottoken: 8615998851:AAFKypK1CsuGqvpi3ykig1h8pg0AZmfq73g
            chatid: "-5207549205"
            disable_notification: false
            disable_web_page_preview: false
            protect_content: false
          disableResolveMessage: false
