apiVersion: 1
policies:
  - orgId: 1
    receiver: telegram-alerts
    group_by: ['alertname', 'grafana_folder', 'pod']
    routes:
      - receiver: telegram-alerts
        object_matchers:
          - ["severity", "=", "critical"]
