apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: status-page
  template:
    metadata:
      labels:
        app: status-page
    spec:
      containers:
      - name: status-page-container
        image: <your-ECR-url>/yoav-statuspage:latest # Replace with your actual ECR image URL
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: <your-redis-endpoint> # Replace with your actual Redis endpoint

        - name: REDIS_PORT
          value: "6379"

        - name: DB_HOST
          value: <your-db-endpoint> # Replace with your actual DB endpoint

        - name: DB_NAME
          value: statuspage

        - name: DB_USER
          value: yoav_admin

        - name: DB_PASSWORD
          value: <your-db-password> # Replace with your actual DB password or use Kubernetes Secrets for better security or amazon secrets manager

        - name: ALLOWED_HOSTS
          value: "*"

        - name: GUNICORN_CMD_ARGS
          value: "--bind 0.0.0.0:8000 --timeout 300"

        - name: DEBUG
          value: "True"

        - name: REDIS_SSL
          value: "False"

        - name: AWS_STORAGE_BUCKET_NAME
          value: <your-s3-bucket-name> # Replace with your actual S3 bucket name

        - name: AWS_S3_REGION_NAME
          value: "us-east-1"
          
        - name: USE_S3
          value: "True"  