apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-page-scheduler
  template:
    metadata:
      labels:
        app: status-page-scheduler
    spec:
      containers:
      - name: scheduler-container
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/yoav_project_ecr:latest
        imagePullPolicy: Always
        command: ["python", "manage.py", "rqscheduler"]

        env:
        - name: REDIS_HOST
          value: master.yoav-redis-subnet-group.7fftml.use1.cache.amazonaws.com

        - name: REDIS_PORT
          value: "6379"
          
        - name: DB_HOST
          value: yoav-project-db.cx248m4we6k7.us-east-1.rds.amazonaws.com

        - name: DB_NAME
          value: postgres

        - name: DB_USER
          value: postgres

        - name: DB_PASSWORD
          value: '#Aa123456#'

        - name: ALLOWED_HOSTS
          value: "*"

        - name: DEBUG
          value: "True"

        - name: REDIS_SSL
          value: "True"