apiVersion: v1
kind: Service
metadata:
  name: status-page-app
spec:
  type: LoadBalancer
  selector:
    app: status-page
  ports:
    - name: https
      port: 443
      targetPort: 8000
    - name: custom-port
      port: 8000
      targetPort: 8000
    - name: http
      port: 80          
      targetPort: 8000